name: gas_lift_env
channels:
  - snowflake
dependencies:
  - matplotlib
  - numpy
  - pandas
  - plotly
  - pulp
  - python-dotenv
  - scikit-learn
  - scipy
  - snowflake-connector-python
  - snowflake-snowpark-python
  - streamlit

